In [1]:
import pandas as pd
import os
import numpy as np
import warnings
from selenium import webdriver
from selenium.webdriver.chrome.service import Service 
from selenium.webdriver.support.ui import Select, WebDriverWait
import chromedriver_autoinstaller
warnings.filterwarnings('ignore')
pd.set_option('future.no_silent_downcasting', True)
pd.set_option('display.max_columns', None)
service = Service(chromedriver_autoinstaller.install())
from unidecode import unidecode
from sqlalchemy import create_engine
import time

engine = create_engine('mysql+pymysql://viabilidade:senha_segura123#@10.0.15.243:3306/desenvolvimento_viabilidade')

def converter_velocidade(valor):
    if not isinstance(valor, str) or len(valor) < 2:
        return None
    numero, unidade = valor[:-1], valor[-1]
    try:
        numero = float(numero.replace(',', '.'))
        if unidade == 'M':
            return numero
        elif unidade == 'G':
            return numero * 1000
        elif unidade == 'K':
            return numero / 1000
    except ValueError:
        return None
    return None

## PRECOS VTAL
precos_vtal = pd.read_excel('precos_vtal.xlsx')
## ID PROVEDORES
id_provedores = pd.read_excel('arquivos\id_provedores.xlsx')
## ESTACOES ENTREGAS
estacoes_entregas = pd.read_excel('arquivos\estacoes_entregas.xlsx')
## CAPACITY FIXA
capacity_fixa = pd.read_excel('arquivos\capacity_fixa.xlsx')
## CAPACITY MOVEL
try:
    custo_nfv = pd.read_sql('SELECT * FROM custos_nfv', engine)
    custo_nfv.to_excel('./arquivos/custos_nfv.xlsx',index=False)
    capacity_funil = pd.read_sql('SELECT * FROM capacity_funil', engine)
    capacity_funil.to_excel('arquivos\capacity_funil.xlsx',index=False)
except:
    capacity_funil = pd.read_excel('arquivos\capacity_funil.xlsx')
    custo_nfv = pd.read_excel('./arquivos/custos_nfv.xlsx')
## CAPACITY NET/SDH
capacity = pd.read_excel('arquivos\capacity.xlsx')
## ID TECNOLOGIA/FACILIDADE
id_tec_facilidade = pd.read_excel('arquivos\id_tecnologia_facilidades.xlsx')
## ESTACOES DE ENTREGA
estacoes_entregas = pd.read_excel('arquivos\estacoes_entregas.xlsx')
## CIDADES BB
cidades = pd.read_excel('./arquivos/cidades_bbip.xlsx')
## TABELA CUSTO MEDIANO
tabela_custo_mediano = pd.read_excel('./arquivos/AMOSTRA_CUSTO_MEDIANO.xlsx')
municipio_localidade = pd.read_excel('./arquivos/municipio_localidade.xlsx')
consulta_banda = pd.read_excel('./arquivos/consulta_banda.xlsx')
facilidades = pd.read_excel('./arquivos/facilidades_tecnologia_prioridade.xlsx').sort_values('PRIORIDADE',ascending=True).fillna('')
municipio_estacao = pd.read_excel('./arquivos/bb_municipio_estacao.xlsx')
estacoes_uf = pd.read_excel('./arquivos/estacoes_entregas.xlsx')
tecnologia_restricao = pd.read_excel('./arquivos/tecnologia_restricao.xlsx')
try:
    valores_ethernet = pd.read_sql("""
        SELECT *

        FROM valores_terceiros_eth_filtered

        WHERE CUSTO_MENSAL <> 0
        GROUP BY SIGLA_MUNICIPIO,PROVEDOR,VELOCIDADE, PRAZO
    """, engine)
    valores_ethernet.to_csv('valores_ethernet.csv')
except:
    valores_ethernet = pd.read_csv('valores_ethernet.csv')

# valores_ethernet = pd.read_sql('SELECT * FROM valores_terceiros_eth_filtered', engine)

valores_ethernet["VEL"] = valores_ethernet["VELOCIDADE"].apply(converter_velocidade)

valores_ethernet = valores_ethernet[(valores_ethernet.PRAZO == '24 MESES') & pd.notna(valores_ethernet.VEL)]

In [ ]:
## SEVS TEIA
df_sevs = pd.read_csv(r"C:\Users\F257064\Downloads\Backlog_total.csv",sep=';')
## GERA ARQUIVO MODELO PARA RODAR NO MAPINFO
df_mapinfo = pd.read_excel('modelo_mapinfo_nf3.xlsx')
df_mapinfo = df_mapinfo.drop(df_mapinfo.index)
df_mapinfo[['SEV','LATITUDE','LONGITUDE']] = df_sevs[['SEV','LATITUDE','LONGITUDE']]
df_mapinfo.to_excel('modelo_mapinfo_nf3.xlsx',index=False)

In [ ]:
## SEVS FECHAMENTO AUTOMATICO NFV1
df_fec_lot_aut = pd.read_csv(r"C:\Users\F257064\Documents\Codes\atualizacao nfv automatico\NEW_NFV\fechamento_lote_nfv.csv",sep=';')
## SEVS QUE FORAM INDICADA COMO MANUAL NFV1
df_man_lot_aut = pd.read_excel(r"C:\Users\F257064\Documents\Codes\atualizacao nfv automatico\NEW_NFV\fechamento_nfv_lote_manual.xlsx")
## ARQUIVO RETORNO MAPINFO VTAL
df_vtal = pd.read_excel(r"C:\Users\F257064\Downloads\ARQUIVOS ORCOM 8\ARQUIVOS ORCOM\MODELO_ARQUIVO_VTAL_final.xlsx").fillna(0)
## PASTA COM ARQUIVOS DE ORCAMENTO
caminho = r"C:\Users\F257064\Downloads\ARQUIVOS ORCOM 8\ARQUIVOS ORCOM"
arquivos = os.listdir(caminho)

for i, v in df_sevs.iterrows():
    if v.VELOCIDADE[-4] == 'M':
        df_sevs.at[i,'VEL'] = int(v.VELOCIDADE[:-4])
    elif v.VELOCIDADE[-4] == 'G':
        df_sevs.at[i,'VEL'] = (int(v.VELOCIDADE[:-4])) * 1000
    elif v.VELOCIDADE[-4] == 'K':
        df_sevs.at[i,'VEL'] = (int(v.VELOCIDADE[:-4])) / 1000

    aux = municipio_localidade[municipio_localidade.SIGLA_LOC == v.CNL]
    if len(aux) > 0:
        df_sevs.at[i,'CNL'] = aux.CNL.values[0]
    else:
        print(f'{v.SEV} nao encontrou CNL')
        
    
valores_ethernet = valores_ethernet[valores_ethernet.VEL.isin(df_sevs.VEL.unique().tolist())]

In [4]:
########## PRECIFICA VTAL

for index, value in df_sevs.iterrows():
    try:

        if df_vtal[df_vtal.SEV == value.SEV].VTAL500M.values[0] != 0:
            aux_vtal = precos_vtal[(precos_vtal.CNL == value.CNL) & (precos_vtal.VELOCIDADE >= value.VEL) & (precos_vtal.PRAZO >= 24)].sort_values('VELOCIDADE', ascending=True)
            df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'VIAVEL'
            df_sevs.at[index, 'INSTALACAO_VTAL'] = aux_vtal.INST_500M.values[0]
            df_sevs.at[index, 'MENSALIDADE_VTAL'] = aux_vtal.MENSALIDADE.values[0]
        elif df_vtal[df_vtal.SEV == value.SEV].VTAL1K.values[0] != 0:
            aux_vtal = precos_vtal[(precos_vtal.CNL == value.CNL) & (precos_vtal.VELOCIDADE >= value.VEL) & (precos_vtal.PRAZO >= 24)].sort_values('VELOCIDADE', ascending=True)
            df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'VIAVEL'
            df_sevs.at[index, 'INSTALACAO_VTAL'] = aux_vtal.INST_1KM.values[0]
            df_sevs.at[index, 'MENSALIDADE_VTAL'] = aux_vtal.MENSALIDADE.values[0]
        elif df_vtal[df_vtal.SEV == value.SEV].VTAL2K.values[0] != 0:
            aux_vtal = precos_vtal[(precos_vtal.CNL == value.CNL) & (precos_vtal.VELOCIDADE >= value.VEL) & (precos_vtal.PRAZO >= 24)].sort_values('VELOCIDADE', ascending=True)
            df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'VIAVEL'
            df_sevs.at[index, 'INSTALACAO_VTAL'] = aux_vtal.INST_2KM.values[0]
            df_sevs.at[index, 'MENSALIDADE_VTAL'] = aux_vtal.MENSALIDADE.values[0]
        elif df_vtal[df_vtal.SEV == value.SEV].VTAL3K.values[0] != 0:
            aux_vtal = precos_vtal[(precos_vtal.CNL == value.CNL) & (precos_vtal.VELOCIDADE >= value.VEL) & (precos_vtal.PRAZO >= 24)].sort_values('VELOCIDADE', ascending=True)
            df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'VIAVEL'
            df_sevs.at[index, 'INSTALACAO_VTAL'] = aux_vtal.INST_3KM.values[0]
            df_sevs.at[index, 'MENSALIDADE_VTAL'] = aux_vtal.MENSALIDADE.values[0]
        else:
            df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'INVIAVEL'
            df_sevs.at[index, 'INSTALACAO_VTAL'] = 0
            df_sevs.at[index, 'MENSALIDADE_VTAL'] = 0
    except:
        df_sevs.at[index, 'VIABILIDADE_VTAL'] = 'INVIAVEL'
        df_sevs.at[index, 'INSTALACAO_VTAL'] = 0
        df_sevs.at[index, 'MENSALIDADE_VTAL'] = 0

In [5]:
for index, value in df_sevs.iterrows():
    for arq in arquivos:
        if (arq == 'CLIENTE_FERROVIA.csv') | (arq == 'CLIENTE_RODOVIA.csv'):
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            if arq == 'CLIENTE_FERROVIA.csv':
                df_sevs.at[index, 'DIST_CLIENTE_FERROVIA'] = float(df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0])
            else:
                df_sevs.at[index, 'DIST_CLIENTE_ROD'] = float(df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0])
        elif arq == 'FIXA_EST.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'ESTACAO_FIXA'] = df_aux[df_aux.Origem == value.SEV]['Destino'].values[0]
            df_sevs.at[index, 'DIST_ESTACAO_FIXA'] = df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0]
        elif arq == 'FIXA_FERROVIA.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'CRUZAMENTO_FERROVIA_FIXA'] = len(df_aux[df_aux.Origem == value.SEV])
        elif arq == 'FIXA_RODOVIA.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'CRUZAMENTO_ROD_FIXA'] = len(df_aux[df_aux.Origem == value.SEV])
        elif arq == 'FIXA_TEC.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'TEC_FIXA'] = df_aux[df_aux.Origem == value.SEV].Destino.values[0].replace('SDH / SDH', 'SDH').replace('SDH / SDH / SDH', 'SDH').replace('FO EDD MOVEL / SDH', 'SDH').replace('FO EDD MOVEL / FO EDD MOVEL / SDH / SDH', 'SDH').replace('DWDM / FO EDD FIXA / SDH', 'FO EDD FIXA').replace('DWDM / SDH', 'SDH').replace('GPON MOVEL / SDH', 'SDH').replace('FO EDD FIXA / FO EDD FIXA / FO EDD FIXA / SDH / SDH / SDH', 'FO EDD FIXA').replace('FO EDD FIXA / FO EDD FIXA / SDH / SDH', 'FO EDD FIXA').replace('FO EDD FIXA / GPON FIXA', 'FO EDD FIXA').replace('DWDM / FO EDD FIXA', 'FO EDD FIXA').replace('FO EDD FIXA / FO EDD FIXA / FO EDD FIXA / SDH', 'FO EDD FIXA').replace('FO EDD FIXA / SDH', 'FO EDD FIXA').replace('SDH / SDH', 'SDH').replace('FO EDD MOVEL / SDH', 'SDH').replace('FO EDD FIXA / FO EDD FIXA', 'FO EDD FIXA').replace('FO EDD FIXA / FO EDD MOVEL', 'FO EDD FIXA').replace('GPON FIXA / GPON FIXA', 'GPON FIXA').replace('FO EDD NET / GPON NET', 'FO EDD NET').replace('GPON FIXA / SDH', 'GPON FIXA')
        elif arq == 'MOVEL_EST.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'ESTACAO_MOVEL'] = df_aux[df_aux.Origem == value.SEV].Destino.values[0]
            df_sevs.at[index, 'DIST_ESTACAO_MOVEL'] = df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0]
        elif arq == 'MOVEL_FERROVIA.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'CRUZAMENTO_FERROVIA_MOVEL'] = len(df_aux[df_aux.Origem == value.SEV])
        elif arq == 'MOVEL_RODOVIA.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'CRUZAMENTO_ROD_MOVEL'] = len(df_aux[df_aux.Origem == value.SEV])
        elif arq == 'MOVEL_TEC.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'TEC_MOVEL'] = df_aux[df_aux.Origem == value.SEV].Destino.values[0].replace('FO EDD FIXA / FO EDD MOVEL / SDH', 'FO EDD MOVEL').replace('FO EDD MOVEL / SDH', 'FO EDD MOVEL').replace('GPON MOVEL / SDH', 'GPON MOVEL').replace('DWDM / FO EDD MOVEL', 'FO EDD MOVEL').replace('GPON FIXA / GPON MOVEL', 'GPON MOVEL').replace('GPON MOVEL / GPON PLUS MOVEL', 'GPON PLUS MOVEL').replace('FO EDD MOVEL / FO EDD MOVEL / FO EDD MOVEL / SDH / SDH', 'FO EDD MOVEL').replace('FO EDD FIXA / FO EDD MOVEL', 'FO EDD MOVEL').replace('FO EDD MOVEL / FO EDD MOVEL', 'FO EDD MOVEL').replace('FO EDD MOVEL / SDH', 'FO EDD MOVEL')
        elif arq == 'RESTRICAO_SHOP.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'TIPO_RESTRICAO'] = df_aux[df_aux.Origem == value.SEV].Destino.values[0]
            df_sevs.at[index, 'DISTANCIA_RESTRICAO'] = df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0]
        elif arq == 'TER_GENERICA.csv':
            df_aux = pd.read_csv(fr'{caminho}\{arq}', encoding='latin-1')
            df_sevs.at[index, 'CNL_GENERICA'] = df_aux[df_aux.Origem == value.SEV].Destino.values[0]
            df_sevs.at[index, 'DISTANCIA_GENERICA'] = df_aux[df_aux.Origem == value.SEV]['Resultado_Distância'].values[0]
            if df_sevs.at[index, 'DISTANCIA_GENERICA'] == 0:
                df_sevs.at[index, 'VIAVEL_TERCEIRO_GENERICO'] = 'VIAVEL'
            else:
                df_sevs.at[index, 'VIAVEL_TERCEIRO_GENERICO'] = 'INVIAVEL'

In [6]:
for index, value in df_sevs.iterrows():
    if ((value.DIST_CLIENTE_FERROVIA > 200) & (value.DIST_CLIENTE_ROD > 200)):
        if (value.DIST_ESTACAO_FIXA <= 2000) & (value.CRUZAMENTO_FERROVIA_FIXA == 0) & (value.CRUZAMENTO_ROD_FIXA == 0):
            df_sevs.at[index, 'SITUACAO_FIXA'] = 'OK'
        else:
            df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'

        if (value.DIST_ESTACAO_MOVEL <= 2500) & (value.CRUZAMENTO_FERROVIA_MOVEL == 0) & (value.CRUZAMENTO_ROD_MOVEL == 0):
            df_sevs.at[index, 'SITUACAO_MOVEL'] = 'OK'
        else:
            df_sevs.at[index, 'SITUACAO_MOVEL'] = 'NOK'
    else:
        df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'
        df_sevs.at[index, 'SITUACAO_MOVEL'] = 'NOK'

    if (df_sevs.at[index, 'SITUACAO_FIXA'] == 'NOK') & (df_sevs.at[index, 'SITUACAO_MOVEL'] == 'NOK'):
        df_sevs.at[index, 'SOLUCAO_FINAL'] = 'ENVIAR EQUIPE'

In [7]:
dict_restricao = tecnologia_restricao.assign(CODIGO=lambda x: x['CODIGO'].astype(str).str.strip()).set_index('CODIGO')['TECNOLOGIA'].to_dict()

def traduzir_codigos(valor):
    if pd.isna(valor) or str(valor).strip() == "":
        return ""

    codigos = str(valor).split(";")

    return " / ".join(
        dict_restricao.get(codigo.strip(),f"codigo nao encontrado: {codigo.strip()}")
        for codigo in codigos
    )

df_sevs["TIPO_RESTRICAO"] = df_sevs["TIPO_RESTRICAO"].apply(traduzir_codigos)

In [8]:
for index, value in df_sevs[df_sevs.DISTANCIA_RESTRICAO < 1].iterrows():
    if value.TEC_MOVEL in value.TIPO_RESTRICAO:
        df_sevs.at[index, 'SITUACAO_MOVEL'] = 'NOK'
    if value.TEC_FIXA in value.TIPO_RESTRICAO:
        df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'

    if (df_sevs.at[index, 'SITUACAO_FIXA'] == 'NOK') & (df_sevs.at[index, 'SITUACAO_MOVEL'] == 'NOK'):
        df_sevs.at[index, 'SOLUCAO_FINAL'] = 'ENVIAR EQUIPE'

In [ ]:
for index, value in df_sevs.iterrows():
    print('                        ', end="\r")
    print(value.SEV, end="\r")
    if 'GPON' not in value.TEC_FIXA:
        facilidade = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_NUVEM == value.TEC_FIXA].FACILIDADE.values[0]
        df_sevs.at[index, 'CUSTO_FIXA'] = float(custo_nfv[custo_nfv.FACILIDADE == facilidade].NOVO_ACESSO_1G.values[0])
    else:
        facilidade = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_NUVEM == value.TEC_FIXA].FACILIDADE.values[0]
        df_sevs.at[index, 'CUSTO_FIXA'] = float(custo_nfv[custo_nfv.FACILIDADE == facilidade].NOVO_ACESSO_200M.values[0])

    if 'GPON' not in value.TEC_MOVEL:
        facilidade = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_NUVEM == value.TEC_MOVEL].FACILIDADE.values[0]
        df_sevs.at[index, 'CUSTO_MOVEL'] = float(custo_nfv[custo_nfv.FACILIDADE == facilidade].NOVO_ACESSO_1G.values[0])
    else:
        facilidade = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_NUVEM == value.TEC_MOVEL].FACILIDADE.values[0]
        df_sevs.at[index, 'CUSTO_MOVEL'] = float(custo_nfv[custo_nfv.FACILIDADE == facilidade].NOVO_ACESSO_200M.values[0])


for index, value in df_sevs.iterrows():
    if value.UF in ['SP','RJ']:
        if (value.DIST_ESTACAO_FIXA > 0):
            df_sevs.at[index, 'CUSTO_FIXA'] = float(value.CUSTO_FIXA + (((value.DIST_ESTACAO_FIXA) * 1.4) * 17))
        if (value.DIST_ESTACAO_MOVEL > 0) & ((value.TEC_MOVEL != 'FO EDD DC') & (value.TEC_MOVEL != 'FO EDD PV')):
            df_sevs.at[index, 'CUSTO_MOVEL'] = float(value.CUSTO_MOVEL + (((value.DIST_ESTACAO_MOVEL) * 1.4) * 17))
        elif (value.DIST_ESTACAO_MOVEL > 500) & (value.TEC_MOVEL == 'FO EDD DC') | (value.TEC_MOVEL == 'FO EDD PV'):
            df_sevs.at[index, 'CUSTO_MOVEL'] = float(value.CUSTO_MOVEL + (((value.DIST_ESTACAO_MOVEL - 500) * 1.4) * 17))
    else:
        if value.DIST_ESTACAO_FIXA > 0:
            df_sevs.at[index, 'CUSTO_FIXA'] = float(value.CUSTO_FIXA + (((value.DIST_ESTACAO_FIXA) * 1.4) * 14))
        if (value.DIST_ESTACAO_MOVEL > 0) & ((value.TEC_MOVEL != 'FO EDD DC') & (value.TEC_MOVEL != 'FO EDD PV')):
            df_sevs.at[index, 'CUSTO_MOVEL'] = float(value.CUSTO_MOVEL + (((value.DIST_ESTACAO_MOVEL) * 1.4) * 14))
        elif (value.DIST_ESTACAO_MOVEL > 500) & (value.TEC_MOVEL == 'FO EDD DC') | (value.TEC_MOVEL == 'FO EDD PV'):
            df_sevs.at[index, 'CUSTO_MOVEL'] = float(value.CUSTO_MOVEL + (((value.DIST_ESTACAO_MOVEL - 500) * 1.4) * 14))

In [10]:
value.TEC_FIXA

'FO EDD NET'

In [11]:
for index, value in df_sevs.iterrows():
    if value.SOLUCAO_FINAL != 'ENVIAR EQUIPE':

        if (value.CUSTO_MOVEL <= value.CUSTO_FIXA) | ((value.SITUACAO_MOVEL == 'OK') & (value.SITUACAO_FIXA == 'NOK')):
            if value.SITUACAO_MOVEL == 'OK':
                try:
                    aux_capacidade_funil = capacity_funil[capacity_funil.SITE == value.ESTACAO_MOVEL].BANDA.values[0]
                except:
                    aux_capacidade_funil = 0
                if aux_capacidade_funil >= value.VEL:
                    df_sevs.at[index, 'SOLUCAO_FINAL'] = 'VIAVEL PROPRIO'
                    df_sevs.at[index, 'FACILIDADE_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_MOVEL].FACILIDADE_FECHAMENTO.values[0]
                    df_sevs.at[index, 'ID_FACILIDADE_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_MOVEL].ID.values[0]).replace('.0', '')
                    df_sevs.at[index, 'EMPRESA_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_MOVEL].EMPRESA.values[0]
                    df_sevs.at[index, 'ID_EMPRESA_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_MOVEL].ID_EMPRESA.values[0]).replace('.0', '')
                    df_sevs.at[index, 'TECNOLOGIA_FECHAMENTO'] = value.TEC_MOVEL
                    df_sevs.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
                    df_sevs.at[index, 'CUSTO_ACESSO_PROPRIO'] = value.CUSTO_MOVEL
                    if value.VEL > 100:
                        df_sevs.at[index, 'BBIP'] = f'{estacoes_entregas[estacoes_entregas.UF == value.UF].MUNICIPIO.values[0]}|{estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]}'
                        pass
                    df_sevs.at[index, 'OBS'] = f'ESTACAO {value.ESTACAO_MOVEL}'
                else:
                    df_sevs.at[index, 'SITUACAO_MOVEL'] = 'NOK'

            elif value.SITUACAO_FIXA == 'OK':
                try:
                    if ('NET' in value.TEC_FIXA) | ('SDH' in value.TEC_FIXA):
                        aux_capacity_fixa = capacity[capacity.ESTACAO_ENTREGA == value.ESTACAO_FIXA].CAPACITY_MB.values[0]
                    else:
                        aux_capacity_fixa = capacity_fixa[capacity_fixa.SIGLA_EMBRATEL == value.ESTACAO_FIXA].TOTAL.values[0]
                except:
                    pass
                try:
                    if aux_capacity_fixa >= value.VEL:
                        df_sevs.at[index, 'SOLUCAO_FINAL'] = 'VIAVEL PROPRIO'
                        df_sevs.at[index, 'FACILIDADE_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].FACILIDADE_FECHAMENTO.values[0]
                        df_sevs.at[index, 'ID_FACILIDADE_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].ID.values[0]).replace('.0', '')
                        df_sevs.at[index, 'EMPRESA_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].EMPRESA.values[0]
                        df_sevs.at[index, 'ID_EMPRESA_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].ID_EMPRESA.values[0]).replace('.0', '')
                        df_sevs.at[index, 'TECNOLOGIA_FECHAMENTO'] = value.TEC_FIXA
                        df_sevs.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
                        df_sevs.at[index, 'CUSTO_ACESSO_PROPRIO'] = value.CUSTO_FIXA
                        if value.VEL > 100:
                            df_sevs.at[index, 'BBIP'] = f'{estacoes_entregas[estacoes_entregas.UF == value.UF].MUNICIPIO.values[0]}|{estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]}'
                            pass
                        df_sevs.at[index, 'OBS'] = f'ESTACAO {value.ESTACAO_FIXA}'
                except:
                    df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'
                else:
                    df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'
        elif (value.CUSTO_MOVEL >= value.CUSTO_FIXA) | ((value.SITUACAO_MOVEL == 'NOK') & (value.SITUACAO_FIXA == 'OK')):

            if value.SITUACAO_FIXA == 'OK':
                try:
                    if ('NET' in value.TEC_FIXA) | ('SDH' in value.TEC_FIXA):
                        aux_capacity_fixa = capacity[capacity.ESTACAO_ENTREGA == value.ESTACAO_FIXA].CAPACITY_MB.values[0]
                    else:
                        aux_capacity_fixa = capacity_fixa[capacity_fixa.SIGLA_EMBRATEL == value.ESTACAO_FIXA].TOTAL.values[0]
                except:
                    pass
                try:
                    if aux_capacity_fixa >= value.VEL:
                        df_sevs.at[index, 'SOLUCAO_FINAL'] = 'VIAVEL PROPRIO'
                        df_sevs.at[index, 'FACILIDADE_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].FACILIDADE_FECHAMENTO.values[0]
                        df_sevs.at[index, 'ID_FACILIDADE_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].ID.values[0]).replace('.0', '')
                        df_sevs.at[index, 'EMPRESA_FECHAMENTO'] = id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].EMPRESA.values[0]
                        df_sevs.at[index, 'ID_EMPRESA_FECHAMENTO'] = str(id_tec_facilidade[id_tec_facilidade.TECNOLOGIA_FECHAMENTO == value.TEC_FIXA].ID_EMPRESA.values[0]).replace('.0', '')
                        df_sevs.at[index, 'TECNOLOGIA_FECHAMENTO'] = value.TEC_FIXA
                        df_sevs.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
                        df_sevs.at[index, 'CUSTO_ACESSO_PROPRIO'] = value.CUSTO_FIXA
                        if value.VEL > 100:
                            df_sevs.at[index, 'BBIP'] = f'{estacoes_entregas[estacoes_entregas.UF == value.UF].MUNICIPIO.values[0]}|{estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]}'
                            pass
                        df_sevs.at[index, 'OBS'] = f'ESTACAO {value.ESTACAO_FIXA}'
                except:
                    df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'
                else:
                    df_sevs.at[index, 'SITUACAO_FIXA'] = 'NOK'


###### VERIFICA PROPRIO E COLOCA VIABILIDADE VTAL
for index, value in df_sevs.iterrows():
    if (value.SITUACAO_FIXA == 'NOK') & (value.SITUACAO_MOVEL == 'NOK'):
        df_sevs.at[index, 'SOLUCAO_FINAL'] = 'INVIAVEL MOVEL/FIXA'

        if value.VIABILIDADE_VTAL == 'VIAVEL':
            df_sevs.at[index, 'SOLUCAO_FINAL'] = 'INVIAVEL PROPRIO/VIAVEL VTAL'
            df_sevs.at[index, 'FACILIDADE_FECHAMENTO'] = 'TERCEIROS ETH'
            df_sevs.at[index, 'ID_FACILIDADE_FECHAMENTO'] = '26'
            df_sevs.at[index, 'EMPRESA_FECHAMENTO'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.UF}'].PROVEDOR_TEIA.values[0]
            df_sevs.at[index, 'ID_EMPRESA_FECHAMENTO'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.UF}'].ID.values[0]
            df_sevs.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
            if value.VEL > 100:
                df_sevs.at[index, 'BBIP'] = f'{estacoes_entregas[estacoes_entregas.UF == value.UF].MUNICIPIO.values[0]}|{estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]}'
                pass
            df_sevs.at[index, 'OBS'] = f'FECHAMENTO LPU VTAL'


df_sevs.BBIP = df_sevs.BBIP.fillna('')
df_sevs.SOLUCAO_FINAL = df_sevs.SOLUCAO_FINAL.fillna('')

In [12]:
for index, value in df_sevs.iterrows():
    if value.VIAVEL_TERCEIRO_GENERICO == 'VIAVEL':
        try:
            custo_instalacao_mediano = valores_ethernet[(valores_ethernet.SIGLA_MUNICIPIO == value.CNL) & (valores_ethernet.VEL == value.VEL)].TAXA_INSTALACAO.median()
            custo_mensal_mediano = valores_ethernet[(valores_ethernet.SIGLA_MUNICIPIO == value.CNL) & (valores_ethernet.VEL == value.VEL)].CUSTO_MENSAL.median()
            custo_mensalizado_mediano = (custo_instalacao_mediano / 24) + custo_mensal_mediano
            if (np.isnan(custo_instalacao_mediano)) | (np.isnan(custo_mensal_mediano)) | (np.isnan(custo_mensalizado_mediano)):
                if value.VEL <= 10:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 10M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 10M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 10M'].values[0]
                elif value.VEL <= 50:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 50M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 50M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 50M'].values[0]
                elif value.VEL <= 100:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 100M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 100M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 100M'].values[0]
                elif value.VEL <= 200:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 200M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 200M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 200M'].values[0]
                elif value.VEL <= 300:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 300M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 300M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 300M'].values[0]
                elif value.VEL <= 400:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 400M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 400M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 400M'].values[0]
                elif value.VEL <= 500:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 500M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 500M'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 500M'].values[0]
                elif value.VEL <= 1000:
                    df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE INST - ATÉ 1G'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE MENSAL - ATÉ 1G'].values[0]
                    df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = tabela_custo_mediano[tabela_custo_mediano.CNL == value.CNL]['TERCEIROS LAST MILE - ATÉ 1G'].values[0]

                df_sevs.at[index, 'STATUS_CUSTO_MEDIO'] = 'PRECIFICADO TABELA CUSTO MEDIANO'

            else:
                df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = custo_instalacao_mediano
                df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = custo_mensal_mediano
                df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = custo_mensalizado_mediano
                df_sevs.at[index, 'STATUS_CUSTO_MEDIO'] = 'PRECIFICADO CUSTO MEDIANO VELOCIDADE SOLICITADA'

        except:
            df_sevs.at[index, 'CUSTO_INSTALACAO_MEDIANO'] = 0
            df_sevs.at[index, 'CUSTO_MENSAL_MEDIANO'] = 0
            df_sevs.at[index, 'CUSTO_MENSALIZADO_MEDIANO'] = 0
            df_sevs.at[index, 'STATUS_CUSTO_MEDIO'] = 'PRECO MEDIANO NAO ENCONTRADO'
            df_sevs.at[index, 'STATUS_CUSTO_MEDIO'] = 'INVIAVEL'
            df_sevs.at[index, 'VIAVEL_TERCEIRO_GENERICO'] = 'INVIAVEL'

    else:
        df_sevs.at[index, 'STATUS_CUSTO_MEDIO'] = 'INVIAVEL'

df_sevs[['CUSTO_MENSALIZADO_MEDIANO', 'CUSTO_MENSAL_MEDIANO', 'CUSTO_INSTALACAO_MEDIANO']] = df_sevs[['CUSTO_MENSALIZADO_MEDIANO', 'CUSTO_MENSAL_MEDIANO', 'CUSTO_INSTALACAO_MEDIANO']].fillna(0)

In [13]:
df_sevs_viavel = df_sevs[df_sevs.SEV.isin(df_fec_lot_aut.sequencial.unique().tolist())].copy(deep=True)
df_sevs_man = df_sevs[~df_sevs.SEV.isin(df_fec_lot_aut.sequencial.unique().tolist())].copy(deep=True)

In [14]:
df_sevs_viavel[df_sevs_viavel.SEV == 9508855]

Empty DataFrame
Columns: [ID_ANALISE, ID_TRIAGEM, CAIXA, SEV, CLIENTE, CLIENTE_FINAL, VELOCIDADE, CNL, DATA_DE_INCLUSAO, DATA_DE_TRIAGEM, DATA_FECHAMENTO_TEIA, DIAS, SOLICITANTE, SOLUCIONADOR, PRIORIZAR, FINALIZADO, TIPO_LOGRADOURO, NOME_DO_LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, ESTADO, REGIONAL, CEP, SERVICO, VELOCIDADE_SERV, QTDE_CIRCUITOS, PABX_VIRTUAL, OBS_SOLICITANTE, PONTA_A, LATITUDE, LONGITUDE, CODGEO, INDGEO, FASE, SUBFASE, OBS_PENDENCIA, STATUS_FECHAMENTO, FACILIDADE, PROTOCOLO_GAIA, ABORDADO, FACILIDADE_ABORDADA, PRAZO, PRAZO_MANUAL, JUSTIFICATIVA_PRAZO_MANUAL, DISPONIBILIDADE, RESERVA_BACKBONE_IP, PROTOCOLO_IP, RESERVA_BACKBONE_TELEFONIA, PROTOCOLO_TELEFONIA, ESTACAO_DE_ENTREGA, EMPRESA_FORNECEDORA, CUSTO_TOTAL, MENSALIDADE_TERCEIRO, TAXA_DE_INSTALACAO_TERCEIRO, CUSTO_ACESSO, CUSTO_ACESSO_EQUIPAMENTO, CUSTO_PLANTA_EQUIPAMENTO, CUSTO_PLANTA_REDE_EXTERNA, CUSTO_EXCLUSIVO_ACESSO, RESPOSTA_SEV, ACAO, PROJETO, VEL, VIABILIDADE_VTAL, INSTALACAO_VTAL, MENSALIDADE_VTAL, DIST_CLIENTE_FERROVIA, DIST_CLIENTE_ROD, ESTACAO_FIXA, DIST_ESTACAO_FIXA, CRUZAMENTO_FERROVIA_FIXA, CRUZAMENTO_ROD_FIXA, TEC_FIXA, ESTACAO_MOVEL, DIST_ESTACAO_MOVEL, CRUZAMENTO_FERROVIA_MOVEL, CRUZAMENTO_ROD_MOVEL, TEC_MOVEL, TIPO_RESTRICAO, DISTANCIA_RESTRICAO, CNL_GENERICA, DISTANCIA_GENERICA, VIAVEL_TERCEIRO_GENERICO, SITUACAO_FIXA, SITUACAO_MOVEL, SOLUCAO_FINAL, CUSTO_FIXA, CUSTO_MOVEL, FACILIDADE_FECHAMENTO, ID_FACILIDADE_FECHAMENTO, EMPRESA_FECHAMENTO, ID_EMPRESA_FECHAMENTO, TECNOLOGIA_FECHAMENTO, ESTACAO_ENTREGA, CUSTO_ACESSO_PROPRIO, OBS, BBIP, ...]
Index: []

In [15]:
df_fec_lot_aut.head(5)

,sequencial,latitude,longitude,uf,cnl,facilidade,id_facilidade,provedor,id_provedor,entrega,abordado,custo_de_acesso_proprio,instalacao_terceiros,mensalidade_terceiros,tipo_terceiros,id_da_sev,prazo,bb_ip,hp_bsod,codigo_spe,sinalizacao_sip,protocolo_gaia,obs,justificativa,ID Justificativa,status,tecnologia
0,11062078,"-23,05313","-47,03189",SP,VIN,TERCEIROS ETH,26,UPIX - SP,471,SPO IG,NAO,NaN,"990,0","828,0",3.0,3451789,NaN,NaN,NaN,NaN,NaN,14993551,FECHAMENTO NFV FASE 1/PRECO PADRAO/ ESTACAO EN...,FORA DE REDE,1.0,1,TERCEIRO ETH
1,11090727,"-23,5487003","-46,6368617",SP,SPO,TERCEIROS ETH,26,BRFIBRA,127,SPO IG,NAO,NaN,"800,0","444,4",3.0,3472711,NaN,NaN,NaN,NaN,NaN,14993553,FECHAMENTO NFV FASE 1/PRECO PADRAO/ ESTACAO EN...,FORA DE REDE,1.0,1,TERCEIRO ETH
2,11095570,"-7,14237","-34,88229",PB,JPA,FO GPON RESID ETH PRE VIAVEL,50,CLARO BRASIL,8,JPA TR,NAO,"1001,0",NaN,NaN,NaN,3476428,NaN,NaN,NaN,NaN,NaN,14993554,FECHAMENTO NFV FASE 1/ ESTACAO ENTREGA JPA TR/...,NaN,NaN,1,GPON RES RESID PV
3,11103025,"-1,35818168","-48,3839916",PA,AIU,TERCEIROS ETH,26,IG NETWORKS,146,BLM QB,NAO,NaN,"2100,0","1351,35",3.0,3482587,NaN,NaN,NaN,NaN,NaN,14993555,FECHAMENTO NFV FASE 1/PRECO PADRAO/ ESTACAO EN...,FORA DE REDE,1.0,1,TERCEIRO ETH
4,11143898,"-7,8968375","-35,1763888",PE,PLH,TERCEIROS ETH,26,IG NETWORKS,146,RCE AM,NAO,NaN,"2100,0","1754,02",3.0,3510056,NaN,NaN,NaN,NaN,NaN,14993567,FECHAMENTO NFV FASE 1/PRECO PADRAO/ ESTACAO EN...,FORA DE REDE,1.0,1,TERCEIRO ETH

In [16]:
# =====================================================================
#  LOOP df_fec_lot_aut  -  VERSAO CORRIGIDA
#  Escolhe o MENOR custo entre as opcoes REALMENTE disponiveis (>0).
#  FEC_AUT (fechamento automatico ja existente) e sempre a opcao base;
#  so troca por PROPRIO / VTAL / MEDIANO se forem mais baratos.
# =====================================================================
for index, value in df_fec_lot_aut.iterrows():
    if value.facilidade != 'TERCEIROS ETH':
        continue

    # Custo mensalizado do fechamento automatico ja gravado (opcao base)
    custo_fec_aut = (float(str(value.instalacao_terceiros).replace(',', '.')) / 24) + (float(str(value.mensalidade_terceiros).replace(',', '.')))

    # Guarda os custos originais da resposta de terceiro existente.
    # Esses valores serão usados na observação caso o fechamento seja
    # alterado de TERCEIROS ETH para acesso próprio por orçamento.
    instalacao_terceiro_existente = float(
        str(value.instalacao_terceiros).replace(',', '.')
    )

    mensalidade_terceiro_existente = float(
        str(value.mensalidade_terceiros).replace(',', '.')
    )

    texto_custo_terceiro = (
        f'OPCAO DE TERCEIRO DISPONIVEL: {value.provedor} '
        f'INSTALACAO R$ {instalacao_terceiro_existente:,.2f} / '
        f'MENSALIDADE R$ {mensalidade_terceiro_existente:,.2f} / '
        f'CUSTO MENSALIZADO EM 24 MESES R$ {custo_fec_aut:,.2f}'
    ).replace(',', '#').replace('.', ',').replace('#', '.')

    aux_orcamentos = df_sevs_viavel[df_sevs_viavel.SEV == value.sequencial]
    if len(aux_orcamentos) == 0:
        continue

    # if aux_orcamentos.DISTANCIA_RESTRICAO.values[0] <= 0:
    #     df_sevs_man.at[index, 'SOLUCAO_FINAL'] = f'INVIAVEL RESTRICAO {value.TIPO_RESTRICAO}'
    #     continue

    # --- Custos mensalizados das alternativas (0 = indisponivel) ---
    if aux_orcamentos.VIABILIDADE_VTAL.values[0] == 'VIAVEL':
        custo_vtal = float((aux_orcamentos.INSTALACAO_VTAL.values[0] / 24) + aux_orcamentos.MENSALIDADE_VTAL.values[0])
    else:
        custo_vtal = 0

    if aux_orcamentos.SOLUCAO_FINAL.values[0] == 'VIAVEL PROPRIO':
        custo_proprio = float(aux_orcamentos.CUSTO_ACESSO_PROPRIO.values[0] / 24)
    else:
        custo_proprio = 0

    if aux_orcamentos.STATUS_CUSTO_MEDIO.values[0] != 'INVIAVEL':
        custo_mediano = float(aux_orcamentos.CUSTO_MENSALIZADO_MEDIANO.values[0])
    else:
        custo_mediano = 0

    # --- Monta o dicionario de opcoes: so entra quem tem custo > 0 ---
    opcoes = {}
    if custo_fec_aut > 0:
        opcoes['FEC_AUT'] = custo_fec_aut
    if custo_proprio > 0:
        opcoes['PROPRIO'] = custo_proprio
    if custo_vtal > 0:
        opcoes['VTAL'] = custo_vtal
    if custo_mediano > 0:
        opcoes['MEDIANO'] = custo_mediano

    # Se nao ha nenhuma opcao valida, mantem o fechamento como esta
    if not opcoes:
        continue

    # O orçamento de rede própria tem prioridade sobre qualquer solução de terceiros.
    # Se não houver orçamento próprio válido, mantém a comparação pelo menor custo
    # entre fechamento automático existente, VTAL e custo mediano.
    if custo_proprio > 0:
        escolha = 'PROPRIO'
    else:
        escolha = min(opcoes, key=opcoes.get)

    if escolha == 'FEC_AUT':
        # Mantem o fechamento automatico existente como TERCEIROS ETH,
        # mas informa por que o orçamento de rede própria não foi utilizado.

        motivos_sem_rede_propria = []

        # Verifica travessia de rodovia nas opções fixa e móvel.
        if (
            aux_orcamentos.CRUZAMENTO_ROD_FIXA.values[0] > 0
            or aux_orcamentos.CRUZAMENTO_ROD_MOVEL.values[0] > 0
        ):
            motivos_sem_rede_propria.append(
                'TEMOS TRAVESSIA DE RODOVIA PARA ATENDIMENTO COM REDE PROPRIA'
            )

        # Se ambas as redes estão fora das distâncias máximas,
        # considera que não existe rede própria próxima.
        if (
            aux_orcamentos.DIST_ESTACAO_FIXA.values[0] > 2000
            and aux_orcamentos.DIST_ESTACAO_MOVEL.values[0] > 2500
        ):
            motivos_sem_rede_propria.append(
                'NAO TEMOS REDE PROPRIA PROXIMA'
            )

        # Caso a rede própria não tenha sido aprovada por outro motivo,
        # mantém uma justificativa genérica sem informar algo incorreto.
        if not motivos_sem_rede_propria:
            motivos_sem_rede_propria.append(
                'NAO FOI IDENTIFICADA OPCAO VIAVEL DE REDE PROPRIA'
            )

        df_fec_lot_aut.at[index, 'obs'] = (
            f'FECHAMENTO NFV FASE 1/'
            f'{" / ".join(motivos_sem_rede_propria)}'
        )

    elif escolha == 'PROPRIO':
        df_fec_lot_aut.at[index, 'facilidade'] = aux_orcamentos.FACILIDADE_FECHAMENTO.values[0]
        df_fec_lot_aut.at[index, 'id_facilidade'] = aux_orcamentos.ID_FACILIDADE_FECHAMENTO.values[0]
        df_fec_lot_aut.at[index, 'provedor'] = aux_orcamentos.EMPRESA_FECHAMENTO.values[0]
        df_fec_lot_aut.at[index, 'id_provedor'] = aux_orcamentos.ID_EMPRESA_FECHAMENTO.values[0]
        df_fec_lot_aut.at[index, 'tecnologia'] = aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0]
        df_fec_lot_aut.at[index, 'custo_de_acesso_proprio'] = str(aux_orcamentos.CUSTO_ACESSO_PROPRIO.values[0]).replace('.', ',')
        df_fec_lot_aut.at[index, 'instalacao_terceiros'] = ''
        df_fec_lot_aut.at[index, 'mensalidade_terceiros'] = ''
        df_fec_lot_aut.at[index, 'tipo_terceiros'] = ''
        df_fec_lot_aut.at[index, 'justificativa'] = ''
        df_fec_lot_aut.at[index, 'ID Justificativa'] = ''
        
        if (aux_orcamentos.CUSTO_ACESSO_PROPRIO.values[0] == aux_orcamentos.CUSTO_MOVEL.values[0]):
            if (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] == 'FO EDD DC') | (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] == 'FO EDD PV'):
                metros_construcao = max(0,(aux_orcamentos.DIST_ESTACAO_MOVEL.values[0] - 500) * 1.4)
            elif (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] != 'FO EDD DC') & (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] != 'FO EDD PV'):
                metros_construcao = max(0,(aux_orcamentos.DIST_ESTACAO_MOVEL.values[0]) * 1.4)

            df_fec_lot_aut.at[index, 'obs'] = (
                f'FECHAMENTO NFV FASE 1/'
                f'PRIORIZADO ACESSO PROPRIO POR ORCAMENTO/'
                f'NECESSARIO CONSTRUCAO DE APROXIMADAMENTE '
                f'{metros_construcao:.0f} METROS/'
                f'SITE {aux_orcamentos.ESTACAO_MOVEL.values[0]}/'
                f'{texto_custo_terceiro}'
            )

        elif (aux_orcamentos.CUSTO_ACESSO_PROPRIO.values[0] == aux_orcamentos.CUSTO_FIXA.values[0]):
            metros_construcao = max(0,(aux_orcamentos.DIST_ESTACAO_FIXA.values[0]) * 1.4)
            df_fec_lot_aut.at[index, 'obs'] = (
                f'FECHAMENTO NFV FASE 1/'
                f'PRIORIZADO ACESSO PROPRIO POR ORCAMENTO/'
                f'NECESSARIO CONSTRUCAO DE APROXIMADAMENTE '
                f'{metros_construcao:.0f} METROS/'
                f'{texto_custo_terceiro}'
            )

        else:
            # Proteção caso o custo próprio tenha alguma diferença de precisão
            # e não seja exatamente igual ao custo fixo ou móvel.
            df_fec_lot_aut.at[index, 'obs'] = (
                f'FECHAMENTO NFV FASE 1/'
                f'PRIORIZADO ACESSO PROPRIO POR ORCAMENTO/'
                f'{texto_custo_terceiro}'
            )

    elif escolha == 'MEDIANO':
        df_fec_lot_aut.at[index, 'facilidade'] = 'TERCEIROS ETH'
        df_fec_lot_aut.at[index, 'tecnologia'] = 'TERCEIRO ETH'
        df_fec_lot_aut.at[index, 'id_facilidade'] = 26
        df_fec_lot_aut.at[index, 'provedor'] = 'GENERICO - ACESSO'
        df_fec_lot_aut.at[index, 'id_provedor'] = 1825
        df_fec_lot_aut.at[index, 'instalacao_terceiros'] = str(aux_orcamentos.CUSTO_INSTALACAO_MEDIANO.values[0]).replace('.', ',')
        df_fec_lot_aut.at[index, 'mensalidade_terceiros'] = str(aux_orcamentos.CUSTO_MENSAL_MEDIANO.values[0]).replace('.', ',')
        df_fec_lot_aut.at[index, 'obs'] = 'FECHAMENTO NFV FASE 1'

    elif escolha == 'VTAL':
        df_fec_lot_aut.at[index, 'facilidade'] = 'TERCEIROS ETH'
        df_fec_lot_aut.at[index, 'tecnologia'] = 'TERCEIRO ETH'
        df_fec_lot_aut.at[index, 'id_facilidade'] = 26
        df_fec_lot_aut.at[index, 'provedor'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.uf}'].PROVEDOR_TEIA.values[0]
        df_fec_lot_aut.at[index, 'id_provedor'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.uf}'].ID.values[0]
        df_fec_lot_aut.at[index, 'instalacao_terceiros'] = str(aux_orcamentos.INSTALACAO_VTAL.values[0]).replace('.', ',')
        df_fec_lot_aut.at[index, 'mensalidade_terceiros'] = str(aux_orcamentos.MENSALIDADE_VTAL.values[0]).replace('.', ',')
        df_fec_lot_aut.at[index, 'obs'] = 'FECHAMENTO NFV FASE 1'


df_sevs_man.FACILIDADE_FECHAMENTO = df_sevs_man.FACILIDADE_FECHAMENTO.fillna('')

In [17]:
# =====================================================================
#  LOOP df_sevs_man  -  VERSAO CORRIGIDA
#  Escolhe o MENOR custo entre as opcoes REALMENTE disponiveis (>0).
#  Nunca escolhe GENERICO - ACESSO com custo 0, porque a opcao so
#  entra na disputa se o custo for maior que zero.
# =====================================================================
for index, value in df_sevs_man.iterrows():

    aux_orcamentos = df_sevs_man[df_sevs_man.SEV == value.SEV]
    if value.DISTANCIA_RESTRICAO == 0:
        df_sevs_man.at[index, 'SOLUCAO_FINAL'] = f'INVIAVEL RESTRICAO {value.TIPO_RESTRICAO}'

    # --- Custos mensalizados (0 = indisponivel) ---
    if value.SOLUCAO_FINAL == 'VIAVEL PROPRIO':
        custo_proprio = float(value.CUSTO_ACESSO_PROPRIO / 24)
    else:
        custo_proprio = 0

    if value.VIABILIDADE_VTAL == 'VIAVEL':
        custo_vtal = float((value.INSTALACAO_VTAL / 24) + value.MENSALIDADE_VTAL)
    else:
        custo_vtal = 0

    if value.STATUS_CUSTO_MEDIO != 'INVIAVEL':
        custo_mediano = float(value.CUSTO_MENSALIZADO_MEDIANO)
    else:
        custo_mediano = 0

    # --- So entram na disputa opcoes com custo > 0 ---
    opcoes = {}
    if custo_proprio > 0:
        opcoes['PROPRIO'] = custo_proprio
    if custo_vtal > 0:
        opcoes['VTAL'] = custo_vtal
    if custo_mediano > 0:
        opcoes['MEDIANO'] = custo_mediano

    # Nenhuma opcao valida -> mantem o que ja estava (nao vira GENERICO 0)
    if not opcoes:
        continue

    # O orçamento de rede própria tem prioridade sobre VTAL e custo mediano.
    # Se não houver orçamento próprio válido, mantém a comparação normal
    # pelo menor custo entre as soluções de terceiros disponíveis.
    if custo_proprio > 0:
        escolha = 'PROPRIO'
    else:
        escolha = min(opcoes, key=opcoes.get)

    if escolha == 'PROPRIO':
        # Mantém o orçamento de rede própria como prioridade,
        # mas registra as alternativas de terceiros disponíveis.

        alternativas_terceiros = []

        if custo_mediano > 0:
            instalacao_mediana = float(value.CUSTO_INSTALACAO_MEDIANO)
            mensalidade_mediana = float(value.CUSTO_MENSAL_MEDIANO)
            mensalizado_mediano = float(value.CUSTO_MENSALIZADO_MEDIANO)

            texto_generico = (
                f'OPCAO TERCEIRO GENERICO DISPONIVEL: '
                f'INSTALACAO R$ {instalacao_mediana:,.2f} / '
                f'MENSALIDADE R$ {mensalidade_mediana:,.2f} / '
                f'CUSTO MENSALIZADO EM 24 MESES R$ {mensalizado_mediano:,.2f}'
            ).replace(',', '#').replace('.', ',').replace('#', '.')

            alternativas_terceiros.append(texto_generico)

        if custo_vtal > 0:
            instalacao_vtal = float(value.INSTALACAO_VTAL)
            mensalidade_vtal = float(value.MENSALIDADE_VTAL)
            mensalizado_vtal = float(
                (instalacao_vtal / 24) + mensalidade_vtal
            )

            texto_vtal = (
                f'OPCAO VTAL DISPONIVEL: '
                f'INSTALACAO R$ {instalacao_vtal:,.2f} / '
                f'MENSALIDADE R$ {mensalidade_vtal:,.2f} / '
                f'CUSTO MENSALIZADO EM 24 MESES R$ {mensalizado_vtal:,.2f}'
            ).replace(',', '#').replace('.', ',').replace('#', '.')

            alternativas_terceiros.append(texto_vtal)

        if alternativas_terceiros:
            texto_alternativas = ' / '.join(alternativas_terceiros)

            if str(value.OBS).strip() != '':
                df_sevs_man.at[index, 'OBS'] = (
                    f'{value.OBS}/'
                    f'PRIORIZADO ACESSO PROPRIO POR ORCAMENTO/'
                    f'{texto_alternativas}'
                )
            else:
                df_sevs_man.at[index, 'OBS'] = (
                    f'PRIORIZADO ACESSO PROPRIO POR ORCAMENTO/'
                    f'{texto_alternativas}'
                )

    elif escolha == 'VTAL':
        df_sevs_man.at[index, 'SOLUCAO_FINAL'] = 'VIAVEL VTAL POR CUSTO'
        df_sevs_man.at[index, 'FACILIDADE_FECHAMENTO'] = 'TERCEIROS ETH'
        df_sevs_man.at[index, 'ID_FACILIDADE_FECHAMENTO'] = '26'
        df_sevs_man.at[index, 'EMPRESA_FECHAMENTO'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.UF}'].PROVEDOR_TEIA.values[0]
        df_sevs_man.at[index, 'ID_EMPRESA_FECHAMENTO'] = id_provedores[id_provedores.PROVEDOR_TEIA == f'VTAL - {value.UF}'].ID.values[0]
        df_sevs_man.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
        df_sevs_man.at[index, 'OBS'] = 'FECHAMENTO LPU VTAL'

    elif escolha == 'MEDIANO':
        df_sevs_man.at[index, 'SOLUCAO_FINAL'] = 'VIAVEL CUSTO MEDIANO'
        df_sevs_man.at[index, 'FACILIDADE_FECHAMENTO'] = 'TERCEIROS ETH'
        df_sevs_man.at[index, 'ID_FACILIDADE_FECHAMENTO'] = '26'
        df_sevs_man.at[index, 'EMPRESA_FECHAMENTO'] = 'GENERICO - ACESSO'
        df_sevs_man.at[index, 'ID_EMPRESA_FECHAMENTO'] = 1825
        df_sevs_man.at[index, 'ESTACAO_ENTREGA'] = estacoes_entregas[estacoes_entregas.UF == value.UF].ESTACAO.values[0]
        df_sevs_man.at[index, 'OBS'] = 'FECHAMENTO LPU MEDIANO'

In [18]:
for index, value in df_sevs_man.iterrows():
    if value.FACILIDADE_FECHAMENTO == 'TERCEIROS ETH':
        df_sevs_man.at[index, 'TECNOLOGIA_FECHAMENTO'] = 'TERCEIRO ETH'

df_sevs_man = df_sevs_man[(df_sevs_man.SERVICO.isin(['BLD - Business Link Direct', 'VPL - VIP LINE',
       'UNV - Rede Única de Dados MPLS', 'VPE - VIP SIP', 'IPVPN - IPVPN/MPLS'])) & (df_sevs_man.CAIXA != 'REANÁLISE DE SEV CONTESTAÇÃO') & (df_sevs_man.PROJETO == 'PORTFOLIO') & (df_sevs_man.ACAO != 'Upgrade') & (df_sevs_man.VEL <= 1000)]

df_sevs_man = df_sevs_man.fillna('')

In [19]:
for index, value in df_sevs_man.iterrows():
    if value.SERVICO != 'VPE - VIP BSOD LIGHT':
        if value.TECNOLOGIA_FECHAMENTO != '':
            if consulta_banda[consulta_banda.TECNOLOGIA == value.TECNOLOGIA_FECHAMENTO].VEL_BBIP.values[0] < value.VEL:
                if value.TECNOLOGIA_FECHAMENTO in facilidades[facilidades.VERIFICA_CAPACITY == 'S'].TECNOLOGIA.tolist():
                    aux_municipio_estacao = municipio_estacao[municipio_estacao.ESTACAO == value.ESTACAO_ENTREGA]
                    if len(aux_municipio_estacao) > 0:
                        df_sevs_man.at[index, 'BBIP'] = f'{aux_municipio_estacao.MUNICIPIO.values[0]}|{aux_municipio_estacao.ESTACAO.values[0]}'
                    else:
                        aux_estacao_uf = estacoes_uf[estacoes_uf.UF == value.UF]
                        df_sevs_man.at[index, 'BBIP'] = f'{aux_estacao_uf.MUNICIPIO.values[0]}|{aux_estacao_uf.ESTACAO.values[0]}'
            else:
                df_sevs_man.at[index, 'BBIP'] = ''
        else:
            df_sevs_man.at[index, 'BBIP'] = ''
    else:
        df_sevs_man.at[index, 'BBIP'] = ''

In [20]:
navegador = webdriver.Chrome(service=service)
navegador.implicitly_wait(5)
navegador.get('http://10.100.1.30/admredes/admredes/RPVB_BLD_Cadastrar_2.asp')
time.sleep(25)

for index, value in df_sevs_man[(df_sevs_man.BBIP != '')].iterrows():
    try:
        navegador.get('http://10.100.1.30/admredes/admredes/RPVB_BLD_Cadastrar_2.asp')
        time.sleep(1)
        if (value.BBIP != None) & (value.BBIP != 'BBIP') & ("ID" not in str(value.BBIP)):
            navegador.find_element('name', 'cliente').send_keys(value.CLIENTE)
            navegador.find_element('name', 'sev').send_keys(value.SEV)
            municipio, estacao = value.BBIP.split('|')
            municipio = unidecode(municipio).upper()
            id_municipio = str(cidades[cidades.CIDADE == municipio].ID.values[0])
            Select(navegador.find_element('id', 'combo1')).select_by_value(id_municipio)
            Select(navegador.find_element('id', 'combo2')).select_by_visible_text(estacao)
            if 'E-ACCESS' in value.SERVICO or 'EPL' in value.SERVICO:
                Select(navegador.find_element('name', 'servico')).select_by_value('EPL')
            else:
                Select(navegador.find_element('name', 'servico')).select_by_value('Internet')
            navegador.find_element('name', 'velocidade').send_keys(int(value.VEL))
            navegador.find_element('xpath', '/html/body/div[6]/font/form/div/table[1]/tbody/tr[2]/td/table[5]/tbody/tr/td/input').click()
            time.sleep(4)
            id_bbip = navegador.find_element('xpath', '/html/body/div[6]/font/form/div/table[1]/tbody/tr[2]/td/table[1]/tbody/tr[1]/td').text[:-4]
            status_bbip = navegador.find_element('xpath', '/html/body/div[6]/font/form/div/table[1]/tbody/tr[2]/td/table[4]/tbody/tr/td[2]/font/b').text
            df_sevs_man.at[index, 'BBIP'] = f'{id_bbip} / {status_bbip}'
    except:
        continue

navegador.close()

In [21]:
for index, value in df_sevs_man.iterrows():
    if 'Indeferido' not in value.BBIP:
        if 'VIAVEL VTAL' in value.SOLUCAO_FINAL or 'VIAVEL PROPRIO' in value.SOLUCAO_FINAL or 'MEDIANO' in value.SOLUCAO_FINAL:
            df_fec_lot_aut.at[len(df_fec_lot_aut), 'sequencial'] = value.SEV
            df_fec_lot_aut.loc[len(df_fec_lot_aut) - 1, ['latitude', 'longitude', 'uf', 'cnl', 'facilidade', 'id_facilidade',
            'provedor', 'id_provedor', 'entrega', 'id_da_sev', 'prazo', 'codigo_spe', 'sinalizacao_sip',
            'protocolo_gaia', 'status']] = [value.LATITUDE, value.LONGITUDE, value.UF, value.CNL, value.FACILIDADE_FECHAMENTO, str(value.ID_FACILIDADE_FECHAMENTO).split('.')[0],
            value.EMPRESA_FECHAMENTO, str(value.ID_EMPRESA_FECHAMENTO).split('.')[0], value.ESTACAO_ENTREGA, value.ID_ANALISE, '', '', '', '0', '1']
            df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'abordado'] = 'NAO'
            if value.FACILIDADE_FECHAMENTO != 'TERCEIROS ETH':
                nova_linha = len(df_fec_lot_aut) - 1
                df_fec_lot_aut.at[nova_linha,'custo_de_acesso_proprio'] = str(value.CUSTO_ACESSO_PROPRIO).replace('.', ',')

                complemento_obs = str(value.OBS).strip()

                if (aux_orcamentos.CUSTO_ACESSO_PROPRIO.values[0] == aux_orcamentos.CUSTO_MOVEL.values[0]):
                    if (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] == 'FO EDD DC') | (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] == 'FO EDD PV'):
                        metros_construcao = max(0,(aux_orcamentos.DIST_ESTACAO_MOVEL.values[0] - 500) * 1.4)
                    elif (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] != 'FO EDD DC') & (aux_orcamentos.TECNOLOGIA_FECHAMENTO.values[0] != 'FO EDD PV'):
                        metros_construcao = max(0,(aux_orcamentos.DIST_ESTACAO_MOVEL.values[0]) * 1.4)

                    texto_obs = (
                        f'FECHAMENTO NFV FASE 1/'
                        f'NECESSARIO CONSTRUCAO DE APROXIMADAMENTE '
                        f'{metros_construcao:.0f} METROS/'
                        f'SITE {value.ESTACAO_MOVEL}'
                    )

                elif value.CUSTO_ACESSO_PROPRIO == value.CUSTO_FIXA:
                    metros_construcao = max(0,(float(value.DIST_ESTACAO_FIXA)) * 1.4)

                    texto_obs = (
                        f'FECHAMENTO NFV FASE 1/'
                        f'NECESSARIO CONSTRUCAO DE APROXIMADAMENTE '
                        f'{metros_construcao:.0f} METROS'
                    )

                else:
                    texto_obs = 'FECHAMENTO NFV FASE 1'

                # Acrescenta a justificativa e os custos das alternativas
                # sem apagar o texto de construção da rede própria.
                if complemento_obs != '':
                    texto_obs = f'{texto_obs}/{complemento_obs}'

                df_fec_lot_aut.at[nova_linha, 'obs'] = texto_obs

                df_fec_lot_aut.at[nova_linha,'tecnologia'] = value.TECNOLOGIA_FECHAMENTO
            else:
                if value.SOLUCAO_FINAL == 'VIAVEL CUSTO MEDIANO':
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'instalacao_terceiros'] = str(value.CUSTO_INSTALACAO_MEDIANO).replace('.', ',')
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'mensalidade_terceiros'] = str(value.CUSTO_MENSAL_MEDIANO).replace('.', ',')
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'tecnologia'] = 'TERCEIRO ETH'
                else:
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'instalacao_terceiros'] = str(value.INSTALACAO_VTAL).replace('.', ',')
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'mensalidade_terceiros'] = str(value.MENSALIDADE_VTAL).replace('.', ',')
                    df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'tecnologia'] = 'TERCEIRO ETH'

                df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'tipo_terceiros'] = 3
                df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'justificativa'] = 'FORA DE REDE'
                df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'ID Justificativa'] = 1
                df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'obs'] = f'FECHAMENTO NFV FASE 1/{value.OBS}'

            if value.BBIP != '':
                df_fec_lot_aut.at[len(df_fec_lot_aut) - 1, 'bb_ip'] = value.BBIP.split(' / ')[0].split(': ')[-1]

In [22]:
df_fec_lot_aut = df_fec_lot_aut.fillna('')

for i, v in df_fec_lot_aut.iterrows():
    df_fec_lot_aut.at[i, 'custo_de_acesso_proprio'] = str(v.custo_de_acesso_proprio).split('.')[0]
    df_fec_lot_aut.at[i, 'instalacao_terceiros'] = str(v.instalacao_terceiros).split('.')[0]
    df_fec_lot_aut.at[i, 'mensalidade_terceiros'] = str(v.mensalidade_terceiros).split('.')[0]
    df_fec_lot_aut.at[i, 'tipo_terceiros'] = str(v.tipo_terceiros).split('.')[0]
    df_fec_lot_aut.at[i, 'ID Justificativa'] = str(v['ID Justificativa']).split('.')[0]
    df_fec_lot_aut.at[i, 'status'] = str(v['status']).split('.')[0]
    df_fec_lot_aut.at[i, 'protocolo_gaia'] = str(v['protocolo_gaia']).split('.')[0]
    df_fec_lot_aut.at[i, 'bb_ip'] = str(v['bb_ip']).split('.')[0]
    df_fec_lot_aut.at[i, 'id_da_sev'] = str(v['id_da_sev']).split('.')[0]
    df_fec_lot_aut.at[i, 'hp_bsod'] = str(v['hp_bsod']).split('.')[0]
    df_fec_lot_aut.at[i, 'sequencial'] = str(v['sequencial']).split('.')[0]

In [23]:

df_fec_lot_aut.to_csv('arquivo_fechamento_at_pos_analise_orc_terc.csv', index=False, sep=';')

for i, v in df_sevs_man.iterrows():
    if len(df_fec_lot_aut[df_fec_lot_aut.sequencial == str(v.SEV)]) == 0:
        if 'INVIAVEL RESTRICAO' in v.SOLUCAO_FINAL:
            df_sevs_man.at[i, 'SOLUCAO_FINAL'] = 'INVIAVEL RESTRICAO'
        else:
            df_sevs_man.at[i, 'SOLUCAO_FINAL'] = 'INVIAVEL'
    else:
        df_sevs_man.at[i, 'SOLUCAO_FINAL'] = 'FECHADO'

df_sevs_man.to_excel('SITUACAO_SEVS.xlsx', index=False)

In [24]:
df_sevs[df_sevs.SEV == 11139769]

Empty DataFrame
Columns: [ID_ANALISE, ID_TRIAGEM, CAIXA, SEV, CLIENTE, CLIENTE_FINAL, VELOCIDADE, CNL, DATA_DE_INCLUSAO, DATA_DE_TRIAGEM, DATA_FECHAMENTO_TEIA, DIAS, SOLICITANTE, SOLUCIONADOR, PRIORIZAR, FINALIZADO, TIPO_LOGRADOURO, NOME_DO_LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, ESTADO, REGIONAL, CEP, SERVICO, VELOCIDADE_SERV, QTDE_CIRCUITOS, PABX_VIRTUAL, OBS_SOLICITANTE, PONTA_A, LATITUDE, LONGITUDE, CODGEO, INDGEO, FASE, SUBFASE, OBS_PENDENCIA, STATUS_FECHAMENTO, FACILIDADE, PROTOCOLO_GAIA, ABORDADO, FACILIDADE_ABORDADA, PRAZO, PRAZO_MANUAL, JUSTIFICATIVA_PRAZO_MANUAL, DISPONIBILIDADE, RESERVA_BACKBONE_IP, PROTOCOLO_IP, RESERVA_BACKBONE_TELEFONIA, PROTOCOLO_TELEFONIA, ESTACAO_DE_ENTREGA, EMPRESA_FORNECEDORA, CUSTO_TOTAL, MENSALIDADE_TERCEIRO, TAXA_DE_INSTALACAO_TERCEIRO, CUSTO_ACESSO, CUSTO_ACESSO_EQUIPAMENTO, CUSTO_PLANTA_EQUIPAMENTO, CUSTO_PLANTA_REDE_EXTERNA, CUSTO_EXCLUSIVO_ACESSO, RESPOSTA_SEV, ACAO, PROJETO, VEL, VIABILIDADE_VTAL, INSTALACAO_VTAL, MENSALIDADE_VTAL, DIST_CLIENTE_FERROVIA, DIST_CLIENTE_ROD, ESTACAO_FIXA, DIST_ESTACAO_FIXA, CRUZAMENTO_FERROVIA_FIXA, CRUZAMENTO_ROD_FIXA, TEC_FIXA, ESTACAO_MOVEL, DIST_ESTACAO_MOVEL, CRUZAMENTO_FERROVIA_MOVEL, CRUZAMENTO_ROD_MOVEL, TEC_MOVEL, TIPO_RESTRICAO, DISTANCIA_RESTRICAO, CNL_GENERICA, DISTANCIA_GENERICA, VIAVEL_TERCEIRO_GENERICO, SITUACAO_FIXA, SITUACAO_MOVEL, SOLUCAO_FINAL, CUSTO_FIXA, CUSTO_MOVEL, FACILIDADE_FECHAMENTO, ID_FACILIDADE_FECHAMENTO, EMPRESA_FECHAMENTO, ID_EMPRESA_FECHAMENTO, TECNOLOGIA_FECHAMENTO, ESTACAO_ENTREGA, CUSTO_ACESSO_PROPRIO, OBS, BBIP, ...]
Index: []